server:
  port: 8084

spring:
  application:
    name: ms-produto
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
  sql:
    init:
      mode: always
  batch:
    jdbc:
      initialize-schema: always