spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: login-route
            uri: http://localhost:8081
            predicates:
              - Path=/login/**

          - id: client-route
            uri: http://localhost:8081
            predicates:
              - Path=/clientes/**
            filters:
              - addDynamicRequestHeaderFuncTeste=X-my-header-from-configuration

          - id: produto-route
            uri: http://localhost:8084
            predicates:
              - Path=/produtos/**

          - id: pedido-route
            uri: http://localhost:8083
            predicates:
              - Path=/pedidos/**
            filters:
              - addDynamicRequestHeaderFuncTeste=X-my-header-from-configuration

          - id: interno-pedido-route
            uri: http://localhost:8083
            predicates:
              - Path=/interno/**

          - id: logistica-route
            uri: http://localhost:8082
            predicates:
              - Path=/logistica/**

app:
  jwt:
    secret: ${JWT_SECRET} # valor do JWT_SECRET está no arquivo .env
  login:
    url: http://localhost:8081