spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      mvc:
        filter:
          FilterSupplier: com.postech.gatewaypostech.infra.security.config.FilterSupplierConfig
        routes:
          - id: login-route
            uri: http://localhost:8081
            predicates:
              - Path=/login/**

          - id: client-route
            uri: http://localhost:8081
            predicates:
              - Path=/clientes/**
            filters:
              - addDynamicRequestHeaderFuncTeste=X-my-header-from-configuration

          - id: produto-route
            uri: http://localhost:8084
            predicates:
              - Path=/produtos/**

          - id: pedido-route
            uri: http://localhost:8083
            predicates:
              - Path=/pedidos/**
            filters:
              - addDynamicRequestHeaderFuncTeste=X-my-header-from-configuration

          - id: logistica-route
            uri: http://localhost:8082
            predicates:
              - Path=/logistica/**
  threads:
    virtual:
      enabled: true
logging:
  level:
    org.springframework.cloud.gateway.server.mvc: DEBUG  # Nível de log detalhado para o Gateway
    org.springframework.web: DEBUG           # Logs adicionais para requisições HTTP
server:
  port: 8080
app:
  jwt:
    secret: ${JWT_SECRET}
  login:
    url: http://localhost:8081
    path: /login

