server:
  port: 8082

spring:
  application:
    name: ms-logistica
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always

services:
  pedido-service:
    url: http://localhost:8083
  open-route-service:
    url: https://api.openrouteservice.org
    api-key: ${OPENROUTE_API_KEY}