spring:

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: admin

logging:
  level:
    br.com.pedido: DEBUG

cliente:
  url: http://localhost:8081

produto:
  url: http://localhost:8084