spring:

  datasource:
    url: jdbc:postgresql://localhost:5434/postech_ecommerce_pedido
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: admin

cliente:
  url: http://localhost:8081

produto:
  url: http://localhost:8084