server:
  port: 8083

spring:
  sql:
    init:
      mode: always

  application:
    name: ms-pedido

  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    defer-datasource-initialization: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 10
          initial-interval: 5000
          multiplier: 2

cliente:
  url: http://localhost:8081

produto:
  url: http://localhost:8084