server:
  port: 8081

spring:
  application:
    name: ms-cliente
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

api:
  security:
    token:
      expiration-hours: 2
      secret: ${JWT_SECRET}
